version: '3.1'

networks:
  web-odoo:
    external: true

services:
  odoo:
    container_name: odoo_NAME
    image: odoo:15.0
    ports:
      - "PORT:8069"
    volumes:
      - /home/user/user-NAME/config:/etc/odoo
      - odoo_NAME-odoo-web-data:/var/lib/odoo
    networks:
      - "web-odoo"
    restart: always
    labels:
      - traefik.http.routers.odoo_NAME.rule=Host(`odoo-NAME.localhost`)
      - traefik.port=80
    command: odoo -i base

volumes:
  odoo-web-data: